package moviemicroservice.movie;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/movie") // This means URL's start with /demo (after Application path)
public class MovieController {
  @Autowired // This means to get the bean called movieRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private MovieRepository movieRepository;

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Movie> getAllMovies() {
    // This returns a JSON or XML with the users
	  System.out.println("hello inside all");
    return movieRepository.findAll();
  }
}
